### PR TITLE
Implement ClipboardManager_getText for js (#676)

### PR DESCRIPTION
**Pull request by tmdh**

### CODE REVIEW

**Review by dima-avdeev-jb — APPROVED** [review]

**Comment by dima-avdeev-jb** [comment]
@tmdh Thanks!

**Comment by eymar** [comment]
Unfortunately, this implementation doesn't work.

Here is its js equivalent:
```js
function getClipboardContent() { 
   var ctext = null; 
   window.navigator.clipboard.readText().then((result) => { 
       console.log("setting the result to - " + result); 
      ctext = result }
    ).catch((e) => console.log("Error = " + e));
   console.log("returning - " + ctext);
   return ctext; 
}
```
It can be tested in Chrome console with "Emulate a focus paged" enabled.

Here is a screenshot with the output:
Screenshot 2023-04-18 at 11 11 18

It can be seen that "return" happens before the callback with the result.
It works like that because "readText" return a Promise - https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText

And the Promise won't be executed synchronously/immediately. 

So we need to revert this PR.

**Comment by dima-avdeev-jb** [comment]
@eymar  Yeah, Thanks!

**Comment by tmdh** [comment]
Sorry, guys. I messed up.

**Pull request merged**
