### PR TITLE
Convert more fun interfaces

### PR DESCRIPTION
**Pull request by Goooler**

### CODE REVIEW

**Review by olonho — COMMENTED** [review]
What's the purpose of this change?

**Comment by Goooler** [comment]
To be more readable and idiomatic, adopt the fun interfaces feature of Kotlin 1.4.

**Comment by olonho** [comment]
Well, we try to keep Skiko pretty basic in used language features (so that Compose compiler plugin can process code calling Skiko properly), and so try to avoid newer language features without extensive testing, and fun interfaces known to be problematic with Compose plugin at the certain moment.

**Comment by Goooler** [comment]
Alright.

**Pull request closed without merging**
