### PR TITLE
Update IOS_SIM_UUID

### PR DESCRIPTION
**Pull request by eymar**
Use `iPhone 14` - `ios 16.4`. The previous UUID didn't work anymore:

Invalid device or device pair: 9C58D5E8-9AE8-4595-A262-35CA4871E886

Updated from here:
<s>https://github.com/futureware-tech/simulator-action/wiki/Devices-macos-13</s>

@dima-avdeev-jb It was my mistake , now better to look at `xcrun simctl list devices`

### CODE REVIEW

**Comment by eymar** [comment]
Please let me know if iPhone 14 ios 16.4 is okay. There are other device and ios versions available.

**Comment by eymar** [comment]
Hm. CI still fails for ios: 
```
Invalid device or device pair: 7C3DDFD9-0477-41D8-BD66-E17FFA85D3A1
```
although it is listed here https://github.com/futureware-tech/simulator-action/wiki/Devices-macos-13

**Comment by eymar** [comment]
@dima-avdeev-jb Do we need to run the simulator action (https://github.com/futureware-tech/simulator-action) ?

```
steps:
  - uses: actions/checkout@v2
  - uses: futureware-tech/simulator-action@v2
    with:
      model: 'iPhone 8'
  - run: flutter drive
  ```
  
  Somehow it used to work without this.

**Comment by dima-avdeev-jb** [comment]
> re-tech/simulator-acti

No, we don't need it

**Comment by dima-avdeev-jb** [comment]
> @dima-avdeev-jb Do we need to run the simulator action (https://github.com/futureware-tech/simulator-action) ?
> 
> ```
> steps:
>   - uses: actions/checkout@v2
>   - uses: futureware-tech/simulator-action@v2
>     with:
>       model: 'iPhone 8'
>   - run: flutter drive
> ```
> 
> Somehow it used to work without this.

No, we don't need

**Review by dima-avdeev-jb — APPROVED** [review]

**Pull request merged**
