### PR TITLE
Add setBitmapsEmbedded

### PR DESCRIPTION
**Pull request by morbno**
For our project we needed to to use bitmaps in fonts, but this method wasn't bound. We had to use reflection in order to access it. We would like to have this method available as public API.

### CODE REVIEW

**Comment by dima-avdeev-jb** [comment]
@morbno Do you have a sample to check how it works?

**Comment by morbno** [comment]
> @morbno Do you have a sample to check how it works?

I'm not sure what you mean by "sample".  Do you want to see the source code?

**Comment by dima-avdeev-jb** [comment]
@morbno I want to check how it works on my machine.
Yes, sample of code, or sample project on GitHub.

**Comment by morbno** [comment]
```Kotlin
import org.jetbrains.skia.*
import java.io.FileOutputStream


fun main() {
    val typeface = Typeface.makeFromName("Terminus (TTF)", style = FontStyle.NORMAL)
    val font = Font(typeface, size = 28f)
    val surface = Surface.makeRasterN32Premul(100, 100)
    val canvas = surface.canvas.also { it.clear(Color.BLACK) }
    val paint = Paint().also { it.color = Color.RED }

    canvas.drawString("Test 1", 10f, 50f, font, paint)

    var image = surface.makeImageSnapshot()
    var pngData = image.encodeToData(EncodedImageFormat.PNG) ?: throw Error("Couldn't encode img as png")
    var pngBytes = pngData.bytes

    FileOutputStream("output1.png").use { fos -> fos.write(pngBytes) }

    font.setBitmapsEmbedded(true)
    canvas.clear(Color.BLACK)
    canvas.drawString("Test 2", 10f, 50f, font, paint)

    image = surface.makeImageSnapshot()
    pngData = image.encodeToData(EncodedImageFormat.PNG) ?: throw Error("Couldn't encode img as png")
    pngBytes = pngData.bytes

    FileOutputStream("output2.png").use { fos -> fos.write(pngBytes) }
}
```
output1
output2
[Terminus.zip](https://github.com/JetBrains/skiko/files/10529901/Terminus.zip)

**Review by dima-avdeev-jb — APPROVED** [review]

**Pull request merged**
