### PR TITLE
[WIP] Add MingwX64 (Windows) support

### PR DESCRIPTION
**Pull request by xolider**
This PR adds support for Windows (MingwX64).
It uses LLVM (Clang) for compiling Skia rather than MSVC. To successfully build the mingwX64 target, you need to have LLVM installed and the "bin" folder in your PATH.

This is a work in progress. At this writing time, it successfully builds native bridge and link it to a static `.lib` library

If you have any comments or ideas to make it stable, please feel free to leave them here :)

I know there is an other opened PR for this goal, but it seems to be out-of-date and not maintained anymore

**UPDATE**: the `compileKotlinMingwX64 `task now completes successfully

### CODE REVIEW

**Comment by xolider** [comment]
To successfully build the mingwX64 target, you need to have LLVM installed and the "bin" folder in your PATH.

**Comment by xolider** [comment]
**UPDATE**: the `compileKotlinMingwX64` task now completes successfully

**Comment by xolider** [comment]
**To do:**

- [ ] Implement the Skia layer
- [ ] Implement the clipboard logic
- [ ] Implement the cursor selector

**Comment by Syrou** [comment]
Looking forward to see this added

**Comment by cvicartadeo** [comment]
> Looking forward to see this added

This error may due to the Skia's compilation method. May be the LLVM solution is not the right one. I would try to compile with MSYS2 Mingw64, but I currently run out of time with my current job.

**Comment by xolider** [comment]
> Looking forward to see this added

This error may due to the Skia's compilation method. Maybe the LLVM solution is not the right one. I would try to compile with MSYS2 Mingw64 to get rid of MSVC, but that means no access to Win32 API. I currently run out of time with my current job to check that

An another possible thing is that the Konan LLVM version is too old. I also tried to compile for linuxX64 and had issues with the provided libc library that was too old comparing my host's one, and lead to incompatibilities issues. As far is I heard, Jetbrains plan to bump LLVM/GCC versions with the next Kotlin 2 compiler

**Pull request closed without merging**
