### PR TITLE
Support touchscreen events on mobile`s browsers

### PR DESCRIPTION
**Pull request by jershell**
Hello. The patch adds touchscreen support. I tested it in Safari and Google Chrome on mobile devices. Can you check the solution?

### CODE REVIEW

**Comment by dima-avdeev-jb** [comment]
Thanks!

**Comment by eymar** [comment]
Similar implementation is necessary in wasmJsMain sourceset to support k/wasm target (browser too).

**Comment by jershell** [comment]
> Similar implementation is necessary in wasmJsMain sourceset to support k/wasm target (browser too).

Very likely. I haven't tested this for wasm. If there are no problems, then i can add wasm too.

**Comment by jershell** [comment]
> Similar implementation is necessary in wasmJsMain sourceset to support k/wasm target (browser too).

Done. I checked it on mobile chrome only. 
Safari not support wasmgc and said me the error =\
```
CompileError: WebAssembly.Module doesn't parse at byte 246: can't get 0th Type's return value
```

**Comment by jershell** [comment]
Hi. Do you have any news?

**Comment by jershell** [comment]
@dima-avdeev-jb Hello. Sorry for bothering. Any news?

**Comment by eymar** [comment]
@jershell Looks good to me! 

Tested k/wasm target in Firefox and Chrome.

**Review by eymar — APPROVED** [review]

**Pull request merged**
