### PR TITLE
Bump Skija 0.91.3 -> 0.91.6

### PR DESCRIPTION
**Pull request by tonsky**
This is needed in our new secret IDE

### CODE REVIEW

**Comment by olonho** [comment]
Generally better keep Skija mostly bindings to Skia API, and not an extending Skia library with own functionality. We could merge this change now, but maybe this code shall better be moved to extension functions in product that need them?

**Comment by tonsky** [comment]
That’s the idea, yes. But CSS shadows are more like de-facto standard than app-specific functionality

**Comment by tonsky** [comment]
How I can I use the new version?

**Comment by olonho** [comment]
https://github.com/JetBrains/skiko/releases/tag/v0.2.34

**Pull request merged**
